[phases.setup]
providers = ["python"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build needed - single file app'"]

[start]
cmd = "python simple_app.py"

[variables]
NIXPACKS_NO_NODEJS = "1"
