# Railway Deployment Configuration
[build]
  builder = "NIXPACKS"
  buildCommand = "echo 'Python only - no frontend build needed'"

[deploy]
  startCommand = "python simple_app.py"
  restartPolicyType = "ON_FAILURE"

[env]
  ENVIRONMENT = "production"
  PYTHONUNBUFFERED = "1"
  NIXPACKS_NO_NODEJS = "1"
