services:
  - type: web
    name: flashcard-app
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python simple_app.py
    buildFilter:
      paths:
      - simple_app.py
      - requirements.txt
      - runtime.txt
      ignoredPaths:
      - frontend/**
      - backend/**
      - package.json
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
