services:
  - type: web
    name: flashcard-app
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements-minimal.txt
    startCommand: python simple_app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
